[2025-02-20T13:45:50.129+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-20T13:45:50.135+0100] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: python_operator_dag_v01.greet manual__2025-02-20T12:45:47.672325+00:00 [queued]>
[2025-02-20T13:45:50.138+0100] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: python_operator_dag_v01.greet manual__2025-02-20T12:45:47.672325+00:00 [queued]>
[2025-02-20T13:45:50.138+0100] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-20T13:45:50.144+0100] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): greet> on 2025-02-20 12:45:47.672325+00:00
[2025-02-20T13:45:50.148+0100] {standard_task_runner.py:72} INFO - Started process 20120 to run task
[2025-02-20T13:45:50.151+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'python_operator_dag_v01', 'greet', 'manual__2025-02-20T12:45:47.672325+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/python_operator_dag.py', '--cfg-path', '/var/folders/d6/rl60yzz90jj_2v0s4gm257780000gn/T/tmprb4qr271']
[2025-02-20T13:45:50.153+0100] {standard_task_runner.py:105} INFO - Job 22: Subtask greet
[2025-02-20T13:45:50.173+0100] {task_command.py:467} INFO - Running <TaskInstance: python_operator_dag_v01.greet manual__2025-02-20T12:45:47.672325+00:00 [running]> on host ajlas-macbook-air.local
[2025-02-20T13:45:50.203+0100] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ajlakorman' AIRFLOW_CTX_DAG_ID='python_operator_dag_v01' AIRFLOW_CTX_TASK_ID='greet' AIRFLOW_CTX_EXECUTION_DATE='2025-02-20T12:45:47.672325+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-20T12:45:47.672325+00:00'
[2025-02-20T13:45:50.203+0100] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-20T13:45:50.204+0100] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-20T13:45:50.204+0100] {logging_mixin.py:190} INFO - Current task name:greet state:running start_date:2025-02-20 12:45:50.135499+00:00
[2025-02-20T13:45:50.204+0100] {logging_mixin.py:190} INFO - Dag name:python_operator_dag_v01 and current dag run status:running
[2025-02-20T13:45:50.204+0100] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-20T13:45:50.205+0100] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
TypeError: greet() missing 2 required positional arguments: 'name' and 'age'
[2025-02-20T13:45:50.211+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-20T13:45:50.211+0100] {logging_mixin.py:190} INFO - Task start:2025-02-20 12:45:50.135499+00:00 end:2025-02-20 12:45:50.210792+00:00 duration:0.075293
[2025-02-20T13:45:50.211+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): greet> dag:<DAG: python_operator_dag_v01> dagrun:<DagRun python_operator_dag_v01 @ 2025-02-20 12:45:47.672325+00:00: manual__2025-02-20T12:45:47.672325+00:00, state:running, queued_at: 2025-02-20 12:45:47.695066+00:00. externally triggered: True>
[2025-02-20T13:45:50.212+0100] {logging_mixin.py:190} INFO - Failure caused by greet() missing 2 required positional arguments: 'name' and 'age'
[2025-02-20T13:45:50.212+0100] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=python_operator_dag_v01, task_id=greet, run_id=manual__2025-02-20T12:45:47.672325+00:00, execution_date=20250220T124547, start_date=20250220T124550, end_date=20250220T124550
[2025-02-20T13:45:50.229+0100] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-20T13:45:50.229+0100] {standard_task_runner.py:124} ERROR - Failed to execute job 22 for task greet (greet() missing 2 required positional arguments: 'name' and 'age'; 20120)
Traceback (most recent call last):
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Users/ajlakorman/Desktop/Data-Mining-Projects/Apache_Airflow/venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
TypeError: greet() missing 2 required positional arguments: 'name' and 'age'
[2025-02-20T13:45:50.256+0100] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-20T13:45:50.264+0100] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-20T13:45:50.265+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
